ajengan_halal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls')),
    path('manajemen-pesanan/', include('manajemen_pesanan.urls')),
    path('', include('main.urls')),
    path('profile/', include('user_profile.urls')),
    path('editors-choice/', include('editors_choice.urls')),
    path('makanan/', include('cards_makanan.urls')),
    path('souvenir/', include('manajemen_souvenir.urls')),
    path('wishlist/', include('wishlist.urls')),
]

authentication/urls.py
from django.urls import path
from authentication.views import login_user, logout_user, register, login_flutter, register_flutter, logout_flutter, user_role_mobile

app_name = 'authentication'

urlpatterns = [
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('register/', register, name='register'),
    path('register_flutter/', register_flutter, name='register_flutter'),
    path('login_flutter/', login_flutter, name='login_flutter'),
    path('logout_flutter/', logout_flutter, name='logout_flutter'),
    path('api/user-role/', user_role_mobile, name='user_role_mobile'),
]

cards_makanan/urls.py
from django.urls import path
from .views import (
    show_restaurants, show_menu, restaurant_list, 
    add_restaurant, delete_restaurant, edit_restaurant,
    add_menu_item, delete_menu_item, edit_menu_item, filter_restaurants, restaurant_list_json, add_restaurant_flutter, delete_restaurant_flutter, menu_items_json
)

app_name = 'cards_makanan'

urlpatterns = [
    path('restaurants/', restaurant_list, name='restaurant_list'),
    path('menu/<uuid:restaurant_id>/', show_menu, name='show_menu'),  # Menu 
    path('edit-restaurant/<uuid:restaurant_id>/', edit_restaurant, name='edit_restaurant'), 
    path('add-restaurant/', add_restaurant, name='add_restaurant'),
    path('delete-restaurant/<uuid:restaurant_id>/', delete_restaurant, name='delete_restaurant'),
    path('add-menu-item/<uuid:restaurant_id>/', add_menu_item, name='add_menu_item'),
    path('edit-menu-item/<uuid:menu_item_id>/', edit_menu_item, name='edit_menu_item'),
    path('delete-menu-item/<uuid:menu_item_id>/', delete_menu_item, name='delete_menu_item'),
    path('filter_restaurants/', filter_restaurants, name='filter_restaurants'),
    path('restaurant_list_json/', restaurant_list_json, name='restaurant_list_json'),
    path('add-restaurant-flutter/', add_restaurant_flutter, name='add_restaurant_flutter'),
    path('delete-restaurant-flutter/<uuid:restaurant_id>/', delete_restaurant_flutter, name='delete_restaurant_flutter'),
    path('menu-items-json/<uuid:restaurant_id>/', menu_items_json, name='menu_items_json'),
]

main/urls.py
from django.urls import path
from cards_makanan.views import show_restaurants, restaurant_list, filter_restaurants

app_name = 'main'

urlpatterns = [
    path('', show_restaurants, name='show_restaurants'),
    path('restaurants/', restaurant_list, name='restaurant_list'),
    path('filter_restaurants/', filter_restaurants, name='filter_restaurants'),
]

user_profile/urls.py
from django.urls import path
from user_profile.views import profile, update_profile_flutter, get_profile_flutter

app_name = 'user_profile'

urlpatterns = [
    path('', profile, name='profile'),
    path('update-profile-flutter/', update_profile_flutter, name='update_profile_flutter'),
    path('get-profile-flutter/', get_profile_flutter, name='get_profile_flutter')
]

wishlist/urls.py
# cards_makanan/urls.py
from django.urls import path
from wishlist.views import toggle_wishlist, get_wishlists, get_menu_item_all

app_name = 'wishlist'
urlpatterns = [
    # URL untuk menampilkan wishlist pengguna
    path('toggle-wishlist/', toggle_wishlist, name='toggle_wishlist'),
    path('get-wishlists/', get_wishlists, name='get_wishlists'),
    path('get-menu-item-all/', get_menu_item_all, name='get_menu_item_all')
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        {% block meta %}
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        {% endblock meta %}
        <script src="https://cdn.tailwindcss.com"></script>
        <link href="https://unpkg.com/flowbite@1.4.7/dist/flowbite.min.css" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'css/global.css' %}" />
        <link href="https://fonts.googleapis.com/css2?family=Rasa:ital,wght@0,300..700;1,300..700&display=swap" rel="stylesheet">
        <!-- add new link/script: db, cdn, fonts, etc. -->
        <!-- <link href='https://fonts.googleapis.com/css?family=Plus Jakarta Sans' rel='stylesheet'> -->

        <script>
            tailwind.config = {
                theme: {
                    extend: {
                        fontFamily: {
                            'rasa': ['Rasa', 'sans-serif'],
                            'plus-jakarta-sans': ['"Plus Jakarta Sans"', 'sans-serif'],
                        },
                    },
                },
            };
        </script>
          <style>
             @keyframes slide-up {
              from {
                opacity: 0;
                transform: translateY(20px);
              }
              to {
                opacity: 1;
                transform: translateY(0);
              }
            }

            .slide-up-animation {
              opacity: 0;
              transform: translateY(20px);
              animation: slide-up 1s forwards;
            }
        </style>
    </head>
    
    <body>
        {% block content %} {% endblock content %}
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
        <script type="text/JavaScript" src="{% static 'js/global.js' %}"></script>
        <script src="https://cdn.jsdelivr.net/npm/dompurify@3.1.7/dist/purify.min.js"></script>
        <script src="https://unpkg.com/flowbite@1.4.7/dist/flowbite.js"></script>
    </body>
</html>

templates/navbar.html
{% load static %}
<nav class="bg-brown-mild dark:bg-brown-mild">
  <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto px-4 py-1">
    <!-- Logo Section -->
    <a href="{% url 'authentication:login' %}" class="flex items-center space-x-3 rtl:space-x-reverse">
      <img src="{% static 'images/web-logo.svg' %}" class="h-16" alt="Logo" />
    </a>

    <!-- Mobile Menu Toggle Button -->
    <button data-collapse-toggle="navbar-search" type="button" class="inline-flex items-center p-2 ml-3 text-sm text-brown-lightest rounded-lg md:hidden hover:bg-brown-darker focus:outline-none focus:ring-2 focus:ring-brown-lightest" aria-controls="navbar-search" aria-expanded="false">
      <span class="sr-only">Open main menu</span>
      <svg class="w-6 h-6" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
        <path fill-rule="evenodd" d="M3 5h14a1 1 0 010 2H3a1 1 0 110-2zm0 6h14a1 1 0 010 2H3a1 1 0 110-2zm0 6h14a1 1 0 010 2H3a1 1 0 110-2z" clip-rule="evenodd"></path>
      </svg>
    </button>

    <!-- Right Side Buttons (Cart, Favorites, Profile) -->
    <div class="flex items-center md:order-2">
      <!-- Cart Button -->
      {% if user.is_authenticated %}
      <a href="{% url 'manajemen_pesanan:create_order' %}" class="relative rounded-full bg-brown-darker p-2 text-brown-lightest hover:text-white focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-brown-darker mr-2">
        <span class="absolute -inset-1.5"></span>
        <span class="sr-only">View cart</span>
        <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
          <path stroke-linecap="round" stroke-linejoin="round" d="M3 3h18l-2 13H5L3 3zm3 16a2 2 0 1 0 4 0H6zm8 0a2 2 0 1 0 4 0h-4z" />
        </svg>
      </a>
      {% endif %}

      <!-- Favorites Button -->
      {% if user.is_authenticated %}
      <a href="{% url 'wishlist:toggle_wishlist' %}" class="relative rounded-full bg-brown-darker p-2 text-brown-lightest hover:text-white focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-brown-darker mr-2">
        <span class="absolute -inset-1.5"></span>
        <span class="sr-only">View favorites</span>
        <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
          <path stroke-linecap="round" stroke-linejoin="round" d="M12 21.35l-1.45-1.32C5.4 15.36 2 12.28 2 8.5 2 5.42 4.42 3 7.5 3c1.74 0 3.41.81 4.5 2.09C13.09 3.81 14.76 3 16.5 3 19.58 3 22 5.42 22 8.5c0 3.78-3.4 6.86-8.55 11.54L12 21.35z" />
        </svg>
     </a>
      {% endif %}

      <!-- Profile Dropdown -->
      <div class="relative ml-3">
        <div>
          <button type="button" class="relative flex rounded-full bg-brown-darker text-sm focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-brown-darker" id="user-menu-button" aria-expanded="false" aria-haspopup="true">
            <span class="absolute -inset-1.5"></span>
            <span class="sr-only">Open user menu</span>
            <img class="h-8 w-8 rounded-full" src="{% static 'images/svg-account.png' %}" alt="">
          </button>
        </div>
        <div id="user-menu" data-username="{{ user.username }}" data-username-url="{% url 'user_profile:profile' %}" data-logout-url="{% url 'authentication:logout' %}" data-login-url="{% url 'authentication:login' %}" data-register-url="{% url 'authentication:register' %}" class="absolute right-0 z-20 mt-2 w-48 origin-top-right rounded-md bg-white py-1 shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none hidden" role="menu" aria-orientation="vertical" aria-labelledby="user-menu-button">
          <a href="{% url 'user_profile:profile' %}" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100" role="menuitem">Your Profile</a>
          <a href="{% url 'authentication:logout' %}" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100" role="menuitem">Sign out</a>
        </div>
      </div>
    </div>

    <!-- Navigation Links and Search Bar -->
    <div class="hidden w-full md:flex md:w-auto md:order-1" id="navbar-search">
      <!-- Navigation Links -->
      <ul class="flex flex-col p-4 mt-4 font-medium border border-brown-lighter rounded-lg bg-brown-darkest md:flex-row md:space-x-8 md:mt-0 md:border-0 md:bg-transparent dark:bg-brown-darker dark:border-brown-darker">
        <li>
          <a href="{% url 'cards_makanan:restaurant_list' %}" class="block py-2 px-3 text-brown-lightest md:bg-transparent md:text-brown-mild md:p-0 md:dark:text-brown-lightest" aria-current="page">Home</a>
        </li>
        <li>
          <a href="{% url 'editors_choice:index_er' %}" class="block py-2 px-3 text-brown-darkest md:hover:bg-transparent md:hover:text-brown-mild md:p-0 md:dark:hover:text-brown-mild dark:text-brown-lightest dark:hover:bg-brown-darker dark:hover:text-brown-lightest md:dark:hover:bg-transparent dark:border-brown-darker">Editor's Choice</a>
        </li>
        <li>
          <a href="{% url 'manajemen_souvenir:show_souvenir' %}" class="block py-2 px-3 text-brown-darkest md:hover:bg-transparent md:hover:text-brown-mild md:p-0 dark:text-brown-lightest md:dark:hover:text-brown-mild dark:hover:bg-brown-darker dark:hover:text-brown-lightest md:dark:hover:bg-transparent dark:border-brown-darker">Souvenir</a>
        </li>
      </ul>
    </div>
  </div>
</nav>