ajengan_halal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls')),
    path('manajemen-pesanan/', include('manajemen_pesanan.urls')),
    path('', include('main.urls')),
    path('profile/', include('user_profile.urls')),
    path('editors-choice/', include('editors_choice.urls')),
    path('makanan/', include('cards_makanan.urls')),
    path('souvenir/', include('manajemen_souvenir.urls')),
    path('wishlist/', include('wishlist.urls')),
]

main/urls.py
from django.urls import path
from cards_makanan.views import show_restaurants, restaurant_list, filter_restaurants

app_name = 'main'

urlpatterns = [
    path('', show_restaurants, name='show_restaurants'),
    path('restaurants/', restaurant_list, name='restaurant_list'),
    path('filter_restaurants/', filter_restaurants, name='filter_restaurants'),
]

manajemen_souvenir/urls.py
from django.urls import path
from manajemen_souvenir.views import show_souvenir, show_json, add_souvenir_entry, edit_souvenir, delete_souvenir
from manajemen_souvenir.views import flutter_add_souvenir_entry, flutter_edit_souvenir, flutter_delete_souvenir
from django.conf import settings
from django.conf.urls.static import static

app_name = 'manajemen_souvenir'

urlpatterns = [
    path('', show_souvenir, name='show_souvenir'),
    path('json/', show_json, name='show_json'),
    path('add-souvenir_entry', add_souvenir_entry, name='add_souvenir_entry'),
    path('edit-souvenir/<uuid:id>', edit_souvenir, name='edit_souvenir'),
    path('delete/<uuid:id>', delete_souvenir, name='delete_souvenir'),
    path('flutter/add-souvenir_entry/', flutter_add_souvenir_entry, name='flutter_add_souvenir_entry'),
    path('flutter/edit-souvenir/<uuid:id>/', flutter_edit_souvenir, name='flutter_edit_souvenir'),
    path('flutter/delete/<uuid:id>/', flutter_delete_souvenir, name='flutter_delete_souvenir'),
]

manajemen_souvenir/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid

# Create your models here.
class SouvenirEntry(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    image = models.ImageField(upload_to='images/')
    name = models.CharField(max_length=255)
    description = models.TextField()

    def __str__(self):
        return self.name

manajemen_souvenir/forms.py
from django.forms import ModelForm
from manajemen_souvenir.models import SouvenirEntry
from django.utils.html import strip_tags
from django import forms
from django.forms import ClearableFileInput

class CustomClearableFileInput(ClearableFileInput):
    template_name = 'custom_clearable_file_input.html'

class SouvenirEntryForm(ModelForm):
    class Meta:
        model = SouvenirEntry
        fields = ["name", "description","image"]
    
    image = forms.ImageField(widget=CustomClearableFileInput)

    def clean_name(self):
        name = self.cleaned_data["name"]
        return strip_tags(name)

    def clean_description(self):
        description = self.cleaned_data["description"]
        return strip_tags(description)
    
    
        
        

manajemen_souvenir/views.py
from django.utils.html import strip_tags
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.core import serializers
from django.shortcuts import render, redirect, reverse, get_object_or_404  
from manajemen_souvenir.forms import SouvenirEntryForm
from manajemen_souvenir.models import SouvenirEntry
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
import uuid, os, json

def show_souvenir(request):
    souvenirs = SouvenirEntry.objects.all()
    return render(request, 'souvenir.html', {'souvenirs': souvenirs})

def show_json(request):
    data = SouvenirEntry.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

@csrf_exempt
@require_POST
def add_souvenir_entry(request):
    if request.method == 'POST':
        # Ambil data dari request POST
        name = strip_tags(request.POST.get("name"))
        description = strip_tags(request.POST.get("description"))
        image_url = strip_tags(request.POST.get("image"))  # URL gambar

        if not name or not description or not image_url:
            return JsonResponse({"status": "error", "message": "Incomplete data"}, status=400)

        # Simpan data ke database
        new_souvenir = SouvenirEntry(name=name, description=description, image=image_url)
        new_souvenir.save()

        return JsonResponse({"status": "success", "message": "Souvenir created"}, status=201)
    else:
        return JsonResponse({"status": "error", "message": "Method not allowed"}, status=405)

def edit_souvenir(request, id):
    # Dapatkan instance souvenir berdasarkan id
    souvenir = get_object_or_404(SouvenirEntry, pk=id)

    if request.method == 'POST':
        # Membuat form dengan data dari request
        form = SouvenirEntryForm(request.POST, request.FILES, instance=souvenir)

        if form.is_valid():
            # Jika ada gambar baru
            if 'image' in request.FILES:
                # Simpan terlebih dahulu gambar baru ke database
                new_image = request.FILES['image']
                unique_name = f"{uuid.uuid4()}_{new_image.name}"
                souvenir.image = new_image
                souvenir.image.name = unique_name
                
                # Simpan form untuk menyimpan perubahan
                form.save()
                
                # Hapus gambar lama setelah menyimpan gambar baru
                if souvenir.image and os.path.isfile(souvenir.image.path):
                    os.remove(souvenir.image.path)

            else:
                # Jika tidak ada gambar baru, tetap simpan form
                form.save()
            
            # Redirect ke halaman show_souvenir setelah update
            return redirect(reverse('manajemen_souvenir:show_souvenir'))
        else:
            print("Form tidak valid:", form.errors)
    else:
        form = SouvenirEntryForm(instance=souvenir)

    context = {
        'form': form,
        'souvenir': souvenir
    }
    return render(request, 'edit_souvenir.html', context)

def delete_souvenir(request, id):
    # Get product berdasarkan id
    souvenir = SouvenirEntry.objects.get(pk = id)
    # Hapus souvenir
    souvenir.delete()
    # Kembali ke halaman awal
    return HttpResponseRedirect(reverse('manajemen_souvenir:show_souvenir'))

@csrf_exempt
def flutter_add_souvenir_entry(request):
    if request.method == 'POST':
        data = json.loads(request.body.decode('utf-8'))
        name = data.get("name")
        description = data.get("description")
        image = data.get("image")

        if not name or not description or not image:
            return JsonResponse({"status": "error", "message": "Incomplete data"}, status=400)

        new_souvenir = SouvenirEntry(name=name, description=description, image=image)
        new_souvenir.save()
        return JsonResponse({"status": "success", "message": "Souvenir created"}, status=201)
    return JsonResponse({"status": "error", "message": "Method not allowed"}, status=405)

@csrf_exempt
def flutter_edit_souvenir(request, id):
    if request.method == 'PUT':
        souvenir = get_object_or_404(SouvenirEntry, pk=id)
        data = json.loads(request.body.decode('utf-8'))
        name = data.get("name")
        description = data.get("description")
        image = data.get("image")

        if not name or not description or not image:
            return JsonResponse({"status": "error", "message": "Incomplete data"}, status=400)

        souvenir.name = name
        souvenir.description = description
        souvenir.image = image
        souvenir.save()
        return JsonResponse({"status": "success", "message": "Souvenir updated"}, status=200)
    return JsonResponse({"status": "error", "message": "Method not allowed"}, status=405)

@csrf_exempt
def flutter_delete_souvenir(request, id):
    if request.method == 'DELETE':
        souvenir = get_object_or_404(SouvenirEntry, pk=id)
        souvenir.delete()
        return JsonResponse({"status": "success", "message": "Souvenir deleted"}, status=200)
    return JsonResponse({"status": "error", "message": "Method not allowed"}, status=405)

manajemen_souvenir/templates/custom_clearable_file_input.html
<div>
    <input type="file" name="{{ widget.name }}" id="{{ widget.id }}" />
</div>

manajemen_souvenir/templates/edit_souvenir.html
{% extends 'base.html' %}
{% load static %}
{% block meta %}
<title>Edit Souvenir</title>
{% endblock meta %}

{% block content %}
<div class="flex flex-col min-h-screen bg-[#e8dcd4]">
  <div class="container mx-auto px-4 py-8 mt-16 max-w-xl">
    <h1 class="text-3xl font-bold text-center mb-8 text-black">Edit Souvenir Entry</h1>
  
    <div class="bg-[#927155] rounded-lg p-6 form-style">
      <form method="POST" class="space-y-6" enctype="multipart/form-data">
          {% csrf_token %}
          {% for field in form %}
              <div class="flex flex-col">
                  <label for="{{ field.id_for_label }}" class="mb-2 font-semibold text-white">
                      {{ field.label }}
                  </label>
                  <div class="mt-1 flex flex-col text-black mb-4 rounded-">
                      {{ field }}
                  </div>
                  {% if field.help_text %}
                      <p class="mt-1 text-sm text-gray-500">{{ field.help_text }}</p>
                  {% endif %}
                  {% for error in field.errors %}
                      <p class="mt-1 text-sm text-red-600">{{ error }}</p>
                  {% endfor %}
              </div>
          {% endfor %}
          <div class="flex justify-center mt-6">
              <button type="submit" class="bg-[#3d200a] text-white font-semibold px-6 py-3 rounded-lg hover:bg-[#cbbcb5] hover:text-[#3d200a] border border-[#3d200a] hover:border-[#3d200a] duration-300 ease-in-out w-full">
                  Edit Souvenir Entry
              </button>
          </div>
      </form>
  </div>
  </div>
</div>
{% endblock %}

manajemen_souvenir/templates/souvenir.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Ajengan Halal | Oleh-Oleh</title>
<script src="https://cdn.jsdelivr.net/npm/dompurify@3.1.7/dist/purify.min.js"></script>
{% endblock meta %}
{% block content %}
{% include 'navbar.html' %}
<div class="overflow-x-hidden px-4 md:px-8 pb-8 pt-24 min-h-screen bg-[#654a2d] flex flex-col">
    <h1 class="text-5xl font-bold p-2 text-center text-[#e8dcd4]">Daftar Oleh-Oleh</h1>
    <div class="flex justify-end mb-6">
      {% if request.user.is_staff %}
      <button data-modal-target="crudModal" data-modal-toggle="crudModal" class="btn text-white bg-[#3d200a] py-2 px-4 rounded-lg transition duration-300 ease-in-out transform hover:-translate-y-1 hover:scale-105" onclick="showModal();">
        Add New Souvenir
      </button>
      {% endif %}
    </div>
    <div id="souvenir_entry_cards"></div>

    <div id="crudModal" tabindex="-1" aria-hidden="true" class="hidden fixed inset-0 z-50 w-full flex items-center justify-center bg-gray-800 bg-opacity-50 overflow-x-hidden overflow-y-auto transition-opacity duration-300 ease-out">
      <div id="crudModalContent" class="relative bg-white rounded-lg shadow-lg w-5/6 sm:w-3/4 md:w-1/2 lg:w-1/3 mx-4 sm:mx-0 transform scale-95 opacity-0 transition-transform transition-opacity duration-300 ease-out">
        <!-- Modal header -->
        <div class="flex items-center justify-between p-4 border-b rounded-t bg-[#654a2d]">
          <h3 class="text-xl font-semibold text-[#e8dcd4]">
            Add New Souvenir Entry
          </h3>
          <button type="button" class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm p-1.5 ml-auto inline-flex items-center" id="closeModalBtn">
            <svg aria-hidden="true" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
              <path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path>
            </svg>
            <span class="sr-only">Close modal</span>
          </button>
        </div>
        <!-- Modal body -->
        <div class="px-6 py-4 space-y-6 form-style bg-[#e8dcd4]">
          <form id="souvenirEntryForm" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="mb-4">
              <label for="name" class="block text-sm font-medium text-[#3d200a]">Souvenir</label>
              <input type="text" id="name" name="name" class="mt-1 block w-full border border-gray-300 rounded-md p-2 hover:border-[#3d200a] text-black bg-white" placeholder="Enter your souvenir" required>
            </div>
            <div class="mb-4">
                <label for="description" class="block text-sm font-medium text-[#3d200a]">Description</label>
                <textarea id="description" name="description" rows="3" class="mt-1 block w-full h-52 resize-none border border-gray-300 rounded-md p-2 hover:border-[#3d200a] text-black bg-white" placeholder="Describe your souvenir" required></textarea>
            </div>
            <div class="mb-4">
              <label for="image" class="block text-sm font-medium text-[#3d200a]">Image</label>
                <div class=" flex justify-center items-center mt-1">
                  <div id="wrapImageAdd" class="w-1/2 mx-3 hidden"></div>
                  <input type="file" id="image" name="image" min="1" max="10" class="mt-1 block w-full border border-gray-300 rounded-md p-2 hover:border-[#3d200a] text-black bg-white" required>
                </div>
            </div>
          </form>
        </div>
        <!-- Modal footer -->
        <div class="flex flex-col space-y-2 md:flex-row md:space-y-0 md:space-x-2 p-6 border-t border-gray-200 rounded-b justify-center md:justify-end bg-[#654a2d]">
          <button type="button" class="bg-red-600 hover:bg-gray-600 text-white font-bold py-2 px-4 rounded-lg" id="cancelButton">Cancel</button>
          <button type="submit" id="submitSouvenirEntry" form="souvenirEntryForm" class="bg-[#3d200a] hover:bg-[#cbbcb5] hover:text-[#3d200a] text-white font-bold py-2 px-4 rounded-lg">Save</button>
        </div>
      </div>
    </div>
</div>

<script>
  async function getSouvenirEntries(){
      return fetch("{% url 'manajemen_souvenir:show_json' %}").then((res) => res.json())
  }

  async function refreshSouvenirEntries() {
    document.getElementById("souvenir_entry_cards").innerHTML = "";
    document.getElementById("souvenir_entry_cards").className = "";
    const souvenirEntries = await getSouvenirEntries();
    let htmlString = "";
    let classNameString = "";

    if (souvenirEntries.length === 0) {
        classNameString = "flex flex-col items-center justify-center min-h-[24rem] p-6";
        htmlString = `
            <div class="flex flex-col items-center justify-center min-h-[24rem] p-6">
                <p class="text-center text-gray-600 mt-4">Belum ada data product pada mental health tracker.</p>
            </div>
        `;
    }
    else {
        classNameString = "columns-1 space-y-14 min-w-min w-3/4 mx-auto"
        souvenirEntries.forEach((item) => {
            const name = DOMPurify.sanitize(item.fields.name);
            const description = DOMPurify.sanitize(item.fields.description);
            const image = `${item.fields.image}`;
            let imageUrl;
            if (image.startsWith("http") || image.startsWith("/")) {
                // Jika image merupakan URL lengkap atau sudah memiliki prefix '/', gunakan langsung
                imageUrl = image;
            } else {
                // Jika bukan, maka asumsikan ini adalah image yang diupload dari web dan perlu path '/media/'
                imageUrl = `/media/${image}`;
            }

            htmlString += `
            <div class="relative break-inside-avoid">
              <div class="relative top-5 bg-[#cbbcb5] shadow-md rounded-lg mb-6 break-inside-avoid flex flex-row border border-gray-200 transition duration-300 ease-in-out transform hover:-translate-y-1 hover:scale-105">
                <div class"parent-section relative">
                  <div class="card flex flex-col md:w-full md:flex-row rounded-lg p-2">
                    <img src="${imageUrl}" alt="${name}" height="200" width="300" class="thumbnail mx-auto rounded-lg">
                    <div class="card-details">
                      
                      <div class="middle mx-2"> 
                        <h2 class="title text-2xl font-bold text-[#3d200a]">${name}</h2>
                        <p class="excerpt text-[#3d200a] overflow-hidden text-ellipsis">${description}</p>
                      </div>

                      {% if request.user.is_staff %}
                      <div class="bottom flex justify-end space-x-1 bottom-1 right-5">
                          <a href="/souvenir/edit-souvenir/${item.pk}" class="hover:bg-[#e8dcd4] text-[#3d200a] font-bold rounded-lg p-2 transition duration-300">
                            Edit
                          </a>
                          <form method="post" action="/souvenir/delete/${item.pk}/" style="display:inline;">
                            {% csrf_token %}
                            <button type="submit" class="hover:bg-gray-400 text-white rounded-full p-2 transition duration-300" onclick="return confirm('Are you sure you want to delete this souvenir?');">
                              <a href="/souvenir/delete/${item.pk}" class="hover:bg-[#e8dcd4] text-red-600 font-bold rounded-lg p-2 transition duration-300">
                                Delete
                              </a>
                            </button>
                          </form>
                      </div>
                      {% endif %}
                    </div>
                  </div>
                </div>                  
              </div>
            </div>
            `;
        });
    }
    document.getElementById("souvenir_entry_cards").className = classNameString;
    document.getElementById("souvenir_entry_cards").innerHTML = htmlString;
  }
  refreshSouvenirEntries();

  const modal = document.getElementById('crudModal');
  const modalContent = document.getElementById('crudModalContent');

  function showModal() {
      const modal = document.getElementById('crudModal');
      const modalContent = document.getElementById('crudModalContent');

      modal.classList.remove('hidden'); 
      setTimeout(() => {
        modalContent.classList.remove('opacity-0', 'scale-95');
        modalContent.classList.add('opacity-100', 'scale-100');
      }, 50); 
  }

  function hideModal() {
      const modal = document.getElementById('crudModal');
      const modalContent = document.getElementById('crudModalContent');

      modalContent.classList.remove('opacity-100', 'scale-100');
      modalContent.classList.add('opacity-0', 'scale-95');

      setTimeout(() => {
        modal.classList.add('hidden');
      }, 150); 

      const wrapImage = document.getElementById("wrapImageAdd");
      wrapImage.classList.add('hidden');
      wrapImage.innerHTML = ``;
  }

  function addSouvenirEntry() {
    fetch("{% url 'manajemen_souvenir:add_souvenir_entry' %}", {
      method: "POST",
      body: new FormData(document.querySelector('#souvenirEntryForm')),
    })
    .then(response => refreshSouvenirEntries())
    
    document.getElementById("souvenirEntryForm").reset(); 
    document.querySelector("[data-modal-toggle='crudModal']").click();
    
    return false;
  }
  
  document.getElementById("cancelButton").addEventListener("click", hideModal);
  document.getElementById("closeModalBtn").addEventListener("click", hideModal);
  document.getElementById("submitSouvenirEntry").onclick = addSouvenirEntry
</script>
{% endblock content %}